### ISSUE TITLE
Add a weekly newsletter

### ISSUE THREAD

**Issue by Zhouzi** [Zhouzi/included-with-xbox-game-pass#24]
The idea is to send a weekly summary of games that were recently added as well as games that are being released soon.

**TODOs**

- [x] Write the sent date to a file to filter new games
- [x] The list of games should include:
	- [x] Platform
	- [ ] Rating
	- [x] Link to the store
- [x] Design email template
- [x] Create the list

**Comment by Zhouzi** [comment]
This is now implemented 🎉
